### ISSUE TITLE
another error yeay

### ISSUE THREAD

**Issue by lucas11222** [face-hh/webx#114]
![image](https://github.com/face-hh/webx/assets/63660708/f2a676a7-8b2b-4fbe-a2fa-17d402b4c5e3)

**Comment by face-hh** [comment]
you already have base-devel installed, remove it from the command

**Comment by lucas11222** [comment]
ok but no close becuse may be another error

**Comment by lucas11222** [comment]
Same....

**Comment by lucas11222** [comment]
i do another issule or no?
