### ISSUE TITLE
Restore Domain Registration key by proving IP ownership

### ISSUE THREAD

**Issue by WeiiswurstDev** [face-hh/webx#118]
I want to suggest a way to recover a registration key:
The server could provide a randomly generated challenge. The owner of the domain must then place that challenge in a new file, such as "dns-recovery.txt", on the server. After proving their ownership this like, they can then generate a new domain key for the domain.

**Comment by face-hh** [comment]
I believe a more reliable way would be to for me to manually re-generate the keys for the lost domains. If the IP field matches the GitHub username connected to Discord (that's where people can contact me easily), then a reset of the key can be done

So in short, not currently planned
