### ISSUE TITLE
Add compatibility with UTF-8

### ISSUE THREAD

**Issue by Timoh5709** [face-hh/webx#119]
I propose, if it's possible, to add compatibility for UTF-8. Because if you try now, it just don't want to update the webpage.

**Comment by face-hh** [comment]
Could you elaborate?

**Comment by Timoh5709** [comment]
I think it would be nice to implement UTF-8 for the non-ASCII characters (like é;è;ô...) with a `<meta charset="utf-8">` in the <head>, because right now Natpture don't update the page when I insert a UTF-8 char, even if I insert the `<meta charset="utf-8">`

**Comment by Timoh5709** [comment]
Nevermind, it was just the DNS server that was too slow
