### ISSUE TITLE
the background is white

### ISSUE THREAD

**Issue by yura88815** [face-hh/webx#12]
OS: Arch Linux x86_64 
Kernel: 6.8.9-arch1-2 
DE: Hyprland 
Theme: Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: breeze-dark [GTK2/3] 
CPU: Intel i5-2310 (4) @ 3.200GHz 
GPU: Intel 2nd Generation Core Processor Family 

![20240531_14h18m22s_grim](https://github.com/face-hh/webx/assets/91333610/9c8d6f82-9efa-49de-abf7-4bc1770ca1ce)

**Comment by face-hh** [comment]
I might've forgot to set a background color for Single. Could you try buss://register.it and let me know if that one has a black background?

**Comment by yura88815** [comment]
here too
![20240531_15h33m26s_grim](https://github.com/face-hh/webx/assets/91333610/e31f5fca-bb0d-4e93-91a4-30add9538d95)

**Comment by emir4169** [comment]
Issue doesnt seem to be fixed.

**Comment by face-hh** [comment]
Will look into it. Until then, set your desktop to dark mode

**Comment by yura88815** [comment]
idk how to do it

**Comment by sastofficial** [comment]
have the same problem

idc if its white but i feel like the text should be black then
![image](https://github.com/face-hh/webx/assets/39431922/5a22b6dd-9d27-4c28-9fd5-7d7417719d88)

**Comment by sastofficial** [comment]
if you take a screenshot of the browser and put it into paint.net and press CTRL + Shift + L you can see stuff
![image](https://github.com/face-hh/webx/assets/39431922/31844982-3491-4ce2-9776-4918ccd597cc)

**Comment by face-hh** [comment]
Fixed in v1.2.1
