### ISSUE TITLE
Requires gtk4 with version >= 4.13, but the latest version available on Ubuntu is 4.6.9?

### ISSUE THREAD

**Issue by FogoVoar** [face-hh/webx#127]
No matter what I do I can't install the latest version of gtk4 using the Ubuntu 22.04.3 package manager, any suggestion?

`pkg-config --modversion gtk4` returns 4.6.9 even after update/upgrade.

**Comment by face-hh** [comment]
Ubuntu 22.04 doesn't support latest GTK. Try upgrading to Ubuntu 24.04 or updating Cargo.toml to use an older GTK version, possibly

**Comment by FogoVoar** [comment]
> Ubuntu 22.04 doesn't support latest GTK. Try upgrading to Ubuntu 24.04 or updating Cargo.toml to use an older GTK version, possibly

Okay, I upgraded to Ubuntu 24.04, apparently it installed successfully. Now a question I didn't expect to ask: How to run the browser from the command line?
I'm using WSL2 by the way.

**Comment by face-hh** [comment]
There should be an executable in the `webx/napture/target/release/` directory
