### ISSUE TITLE
Github domains dont work if the repos default branch isnt called main 

### ISSUE THREAD

**Issue by OhaDerErste** [face-hh/webx#13]
Not much to say about it lol

**Comment by face-hh** [comment]
I don't think this can be fixed without adding latency by doing another request. I'll add it as a note to the readme

**Comment by minidogg** [comment]
> Not much to say about it lol

try out github pages or vercel

**Comment by GStudiosX2** [comment]
> I don't think this can be fixed without adding latency by doing another request. I'll add it as a note to the readme

You could accept these URLs `https://github.com/GStudiosX2/webx/tree/master`

**Comment by face-hh** [comment]
Closing as a solution has been provided
