### ISSUE TITLE
wikapedia pages crash the exe

### ISSUE THREAD

**Issue by blokongithub** [face-hh/webx#14]

**Comment by blokongithub** [comment]
for example ohio.lol

**Comment by face-hh** [comment]
Could you elaborate? Are you trying to access https://wikipedia.org?

**Comment by blokongithub** [comment]
> Could you elaborate? Are you trying to access https://wikipedia.org?

no, if I register a Wikipedia page as a domain on the exe, then I go to the domain (I just made ohio.lol) it crashes the exe (windows)

**Comment by blokongithub** [comment]
![image_2024-05-31_114528969](https://github.com/face-hh/webx/assets/157578374/8da0807c-6f25-404a-89a9-912886af4795)

**Comment by face-hh** [comment]
The HTML used by your site, ohio.lol, is probably not supported.

I don't know how it started looping and not responding though, that usually happens when Lua is present

**Comment by blokongithub** [comment]
ok

**Comment by Siomek101** [comment]
i tried to go to that website of yours, it didnt crash but didnt work, so i copied some html code from that wikipedia page and tried it again: buss://bubble.it (note, i only added the content, not full website)
![image](https://github.com/face-hh/webx/assets/94121336/9f0d15e2-36f9-44fd-b486-a953d58efa55)

**Comment by face-hh** [comment]
Closing this as it provides little to no bug replication value
