### ISSUE TITLE
BUG: Trying to go to any Web X website using Napture dosent work

### ISSUE THREAD

**Issue by realxilliam** [face-hh/webx#144]
**Describe the bug**
Trying to connect to any 

**To Reproduce**
1. Open napture
2. Go to any Web X website (for example dingle.it)
3. Nothing shows

**Expected behavior**
Showing of the dingle.it website

**Screenshots**

![image](https://github.com/face-hh/webx/assets/78660109/7ce6b07c-6767-4d3f-af71-95f0ff80011f)
The napture logs

![image](https://github.com/face-hh/webx/assets/78660109/be6cd605-e227-4905-ac25-2304f7d7111a)
The output

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 (build 22631.3593)

**Additional context**
I have tried it with and without the "buss://" prefix

**Comment by face-hh** [comment]
it has now been fixed
