### ISSUE TITLE
BUG: Link Redirecting Error

### ISSUE THREAD

**Issue by MattiaIlPotenteReal** [face-hh/webx#145]
When i open a page, the website is empty, but if i copy the link and i paste it in a new tab the page will show the text

**To Reproduce**
1. Go to dingle.it
2. search any website you want
3. open the website -> the page will be empty
4. copy the page link
5. paste the link in a new tab -> the page will show the text

![image](https://github.com/face-hh/webx/assets/156002039/69ea60ad-fc14-4813-b94d-16b1c00289bc)
![image](https://github.com/face-hh/webx/assets/156002039/3c20a28d-d197-4114-904a-81141f974e7a)
![image](https://github.com/face-hh/webx/assets/156002039/52de2711-7c6b-48c5-9dc5-a0a76a35ac88)
![image](https://github.com/face-hh/webx/assets/156002039/de021513-9940-4de0-b6be-441e92c156ff)
![image](https://github.com/face-hh/webx/assets/156002039/e0c49d5b-579f-4e69-8b8d-9d4247d55ffc)
![image](https://github.com/face-hh/webx/assets/156002039/7b6d024b-a73d-4a42-b8ef-ac5fcbc3cdd8)

When i open a page, the website is empty, but if i copy the link and i paste it in a new tab the page will show the text

 - OS: Windows
 - Version: 1.2.2

**Comment by QuinceTart10** [comment]
Hmm, but you don't seem to be using Napture 🤔

**Comment by GStudiosX2** [comment]
Isn't that bussigna or whatever the name was

**Comment by face-hh** [comment]
That's a third party browser, please open the issue on their own repository

**Comment by MattiaIlPotenteReal** [comment]
ok
