### ISSUE TITLE
FEATURE: Port to android.
I'

### ISSUE THREAD

**Issue by TaraDaReal** [face-hh/webx#154]
**Is your feature request related to a problem? Please describe.**
I'd like to screw js on my phone.

**Describe the solution you'd like**
Get an .apk on the github releases

**Describe alternatives you've considered**
Make it be a webapp that can be accessed from https like webapp.bussx.lol

**Additional context**
Would be grateful

**Comment by GStudiosX2** [comment]
Napture would likely have to be rewritten to support Android because GTK does not have Android support

**Comment by GStudiosX2** [comment]
But you can run a vnc server within termux with proot-distro and compile napture it won't be a APK or like something you can open up in Android but if you use a vnc viewer and connect to your vnc server you can open it there

**Comment by GStudiosX2** [comment]
This is what I'm doing for now as I don't have a PC I can use yet.!
[Screenshot_20240604-055542.png](https://github.com/face-hh/webx/assets/76548041/ee44950f-0e49-4b11-b21a-b271dfae2323)
