### ISSUE TITLE
BUG: Application wont open on Elementary OS.

### ISSUE THREAD

**Issue by vkhainousky** [face-hh/webx#161]
Application wont open on Elementary OS

1. Execute AppImage
3. See nothing

**Expected behavior**
Application should run

**Desktop:**
 - OS: Elementary OS
 - Version: 7.1

**Comment by dotunwrap** [comment]
@vkhainousky Known issue with the AppImage currently. In the future, please ensure to write a proper title for your issue.

**Comment by vkhainousky** [comment]
Ok.
