### ISSUE TITLE
BUG: Failure at startup

### ISSUE THREAD

**Issue by josephlombardo1** [face-hh/webx#164]
**Describe the bug**
I try to run the .AppImage file and get this.
`./Bussin.Napture-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_ABI_DT_RELR not found (required by /tmp/.mount_BussinIaJNf8/usr/bin/../lib/libmount.so.1)`

**To Reproduce**
Make a fresh install of ubuntu
Install rust using rustup
Run the AppImage

**Expected behavior**
I expected it to run just fine and give me access to the bussin web x

**Screenshots**
I do not have any

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 1.2.2

**Additional context**
none

**Comment by josephlombardo1** [comment]
I might be fixing it now, I am trying to run the installer from source

**Comment by josephlombardo1** [comment]
It failed..

**Comment by josephlombardo1** [comment]
I am compiling glibc as seen in a different issue and I will update you when that's done.

**Comment by face-hh** [comment]
#74 and #120 are related

**Comment by josephlombardo1** [comment]
I am trying out the solution in #87. I will see if it works. It was a fresh linux install after all

**Comment by josephlombardo1** [comment]
It still didn't work. The terminal printed out this(I cut everything before the error):
error: failed to run custom build command for `gdk4-sys v0.8.2

Caused by:
  process didn't exit successfully: /home/user/webx/napture/target/release/build/gdk4-sys-0067f6284b7cdcfb/build-script-build (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GTK4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr

  pkg-config exited with status code 1
  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags gtk4 gtk4 >= 4.14

  The system library gtk4 required by crate gdk4-sys was not found.
  The file gtk4.pc needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.

  HINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing gtk4.pc.

warning: build failed, waiting for other jobs to finish...`

**Comment by josephlombardo1** [comment]
I got it to work with distrobox running ubuntu 24.04 with fuse and the appimage
