### ISSUE TITLE
BUG: register.it doesn't register

### ISSUE THREAD

**Issue by MEGA-Dawg68** [face-hh/webx#167]
**Describe the bug**
When trying to register a website it spits out html, not anything useful. I am assuming it is the captcha, buuuuuuttt Napture is pretty limited

**To Reproduce**
1. Go to register.it
2. Register website
3. See error

**Expected behavior**
I kind of wanted to see the next steps and the private key lol

**Screenshots**
![image](https://github.com/face-hh/webx/assets/140035326/2dce5d1f-95f0-4e5e-b687-08a2333937e4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.2

**Additional context**
I don't know if I am meant to keep that html or what

EDIT: I just recreated the html file and apparently I was blocked
![image](https://github.com/face-hh/webx/assets/140035326/2dd70d0d-5b9d-4cc0-b4c5-5bebcbdb4e93)

**Comment by GStudiosX2** [comment]
#149

**Comment by GStudiosX2** [comment]
> > Duplicate of #149
> 
> Sorry it wasn't the intention. I don't check closed issues as this is obviously not closed

That issue isn't closed though

**Comment by MEGA-Dawg68** [comment]
> > > Duplicate of #149
> > 
> > 
> > Sorry it wasn't the intention. I don't check closed issues as this is obviously not closed
> 
> That issue isn't closed though

Sorry again, I don't know what I was seeing
