### ISSUE TITLE
FEATURE: button to refresh page/clear cache

### ISSUE THREAD

**Issue by Beelzebold** [face-hh/webx#183]
trying to easily view what my site looks like as I edit it would be much easier if I could easily refresh it.
as it stands I have to fiddle with opening and closing the program to get the site to actually update, which makes it very time consuming to try to tweak small things, like the text size of my css for example.

would love to see this get in

**Comment by face-hh** [comment]
You can open it with `file://path`, example: `file://C:\Users\User\Documente\folder_with_index_html`

There's also a refresh button in v1.3.0
