### ISSUE TITLE
BUG: Dosent work in debian 12

### ISSUE THREAD

**Issue by TurboTaur** [face-hh/webx#202]
the app does not start.
the terminal outputs this when i try to run it:
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libadwaita-1.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libgtk-4.so.1)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libgtk-4.so.1)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libpango-1.0.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libcairo.so.2)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libcairo.so.2)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libgio-2.0.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libglib-2.0.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libcrypto.so.3)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libtracker-sparql-3.0.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libvulkan.so.1)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libxkbcommon.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libwayland-client.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libXcursor.so.1)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libmount.so.1)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libxml2.so.2)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libsystemd.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libsqlite3.so.0)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libblkid.so.1)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libgssapi_krb5.so.2)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libicuuc.so.75)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libicuuc.so.75)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libcap.so.2)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libgcrypt.so.20)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libkrb5.so.3)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libk5crypto.so.3)
/home/turbotaur/Darbastalis/Distro/Bussin_Napture-x86_64.appimage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /tmp/.mount_Bussin1yxFYe/usr/bin/../lib/libkrb5support.so.0)

**Comment by KubaPro010** [comment]
Known issue, see #74

**Comment by SticksDev** [comment]
Closing due to known issues. Thank you for your report.
