### ISSUE TITLE
FEATURE: without html/css "only json"

### ISSUE THREAD

**Issue by ghost** [face-hh/webx#205]
**Is your feature request related to a problem? Please describe.**
I think this project is very good, but the question is - why use css/html and not json?

**Describe the solution you'd like**
there are ways to do this through json2html, jsonpath, websockets.

**Describe alternatives you've considered**
I think we can have a more interactive web with json instead of html, css, js.

**Additional context**
None.

**Comment by ZakaHaceCosas** [comment]
You mean to have support for `buss://site.btw/something.json`? Like, being able to have JSON rendered by the browser just like Firefox does?

**Comment by ghost** [comment]
> You mean to have support for buss://site.btw/something.json? Like, being able to have JSON rendered by the browser just like Firefox does?

yes.

**Comment by PepperMarioYT** [comment]
not good idea, please dont implement, bussin napture and the android fan app by RetiredLake would need to code it, and all WebX sites would have to be updated, im literally trying to make a bussin webx site and dont want to have to update to use json.
