### ISSUE TITLE
BUG: The Bussin Napture is Just Name . And It Shows In The Icon An Cude With GTK

### ISSUE THREAD

**Issue by 0XOPx** [face-hh/webx#210]
It Dont Shows

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/8eb103cd-1edc-46a3-8c21-87dcad502a5f)
![image](https://github.com/user-attachments/assets/629b971a-1e7a-4483-80c9-4813e1913690)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
Im Serius It Is Really Happening @face-hh Please Make In The Comments How To Fix IDK.

**Comment by 0XOPx** [comment]
* i downloaded gtk
* i downloaded rust

**Comment by 0XOPx** [comment]
WAIT IF I WILL RUN IT IN TERMINAL

**Comment by SticksDev** [comment]
This does not provide enough information for a bug report. Please re-open with more information if the issue continues to persist.

It also looks like you are running a dev build. Please see the  [releases](https://github.com/face-hh/webx/releases) page for more info and the latest non dev build.

**Comment by 0XOPx** [comment]
I HAVE DEV BULID??? HOW I KNOW?
