### ISSUE TITLE
New domains dont show up on the search engine

### ISSUE THREAD

**Issue by Siomek101** [face-hh/webx#22]
I think that none of the new domains show up, it's like it didn't change since the release of it

**Comment by Siomek101** [comment]
Uhhhh... looking at the domains i can guess why aren't they showing up, some of them are... Not good

**Comment by Siomek101** [comment]
Idea: Make another list of domains that are checked and show up in the search engine

**Comment by Siomek101** [comment]
Note: you should probably check the domains before adding them to the search engine
Example of an unwanted domain:
![image](https://github.com/face-hh/webx/assets/94121336/1de5b438-1216-4885-9d32-a2e6f76bec09)

**Comment by face-hh** [comment]
It has now been fixed
