### ISSUE TITLE
The destination folder is invalid

### ISSUE THREAD

**Issue by the-broz** [face-hh/webx#25]
![image](https://github.com/face-hh/webx/assets/77699093/ff165867-bb05-4e5a-8df5-1dc34cee36c6)
I have C:\Program Files\ in the installation directory. Yet the installer says I don't.

**Comment by the-broz** [comment]
Found a workaround by running the installer as admininstrator and installing to my Secondary (D:\) drive

**Comment by marpisco** [comment]
Hi. What you're doing would extract the files directly on the Program Files folder. That's not valid.

You should do it to something like `C:\Program Files\webx` in order to properly install it.

**Comment by marpisco** [comment]
Also in order to install something to `C:\Program Files` you need Administrator access (or to run an app as Administrator. Your issue is invalid, and you should likely consider closing it.

**Comment by the-broz** [comment]
Even after running as administrator with a sub directory I still get this error 
![image](https://github.com/face-hh/webx/assets/77699093/0a7e4f00-847f-449b-8ecd-05db2ead00a8)
This most likely isn't intended behavior and should be addressed

**Comment by marpisco** [comment]
> This most likely isn't intended behavior and should be addressed

The installer is a PortableApps installer. PortableApps aren't meant to be installed that way (to a program files folder).

Author should probably switch outside of PortableApps.

**Comment by the-broz** [comment]
Overall, it seems like I misunderstood what the installer does and that it **isnt** meant to install as a full app on your device. I have created an installer using InstallForge. Which adds it to the start menu and desktop. This could be a viable method to use for installation.

**Comment by marpisco** [comment]
> I have created an installer using InstallForge.

Could @face-hh use it for releases from now on?

**Comment by QuinceTart10** [comment]
> > I have created an installer using InstallForge.
> 
> Could @face-hh use it for releases from now on?

I don't see why, the current installer works just fine and has pretty good update handling.

**Comment by the-broz** [comment]
Personally, I see it as an alternate installer. Some people might want to have a portable app while others might want it installed to their PC with start menu and desktop shortcuts. Mostly up to preference.
