### ISSUE TITLE
What is the meaning of "Failed due to ratelimit."

### ISSUE THREAD

**Issue by Misnad** [face-hh/webx#27]
Hi. Just a doubt.

**Comment by marpisco** [comment]
A ratelimit is when you've done too many requests to a network or service.

You've most likely hit the limit of requests you could do at a certain amount of time.

**Comment by Misnad** [comment]
OK. But this is not allowing me to create a domain. It keeps showing every time.

**Comment by Siomek101** [comment]
Wait a minute :)

**Comment by face-hh** [comment]
The part of the DNS that allows you to register domains only does so each 1 hour.

Even though the code for the DNS says it should only apply the ratelimit if the request returned a 200, it still applies it

**Comment by marpisco** [comment]
> OK. But this is not allowing me to create a domain. It keeps showing every time.

Yes. You've hit the limit of requests (or someone on your IP address has)

> Wait a minute :)

I'd suggest the same as @Siomek101.

**Comment by marpisco** [comment]
> The part of the DNS that allows you to register domains only does so each 1 hour.

So that would mean you can only register 1 per hour?
