### ISSUE TITLE
Error 400 in creating an domain

### ISSUE THREAD

**Issue by lucas11222** [face-hh/webx#36]
idk what to do

**Comment by face-hh** [comment]
In the IP field, you put your Github or IP (that has the index.html file)
In the Domain field, you put your domain (get it from https://api.buss.lol/tlds)
In the Name field, the name of your website.

**Comment by lucas11222** [comment]
i put my repo https://github.com/lucas11222/Lucas11-Page and same

**Comment by lucas11222** [comment]
is that i put
