### ISSUE TITLE
Error 400 in creating an domain (again becuse is still no fixed)

### ISSUE THREAD

**Issue by lucas11222** [face-hh/webx#37]
i put this https://github.com/lucas11222/Lucas11-Page and is not working

**Comment by lucas11222** [comment]
and sorry for redoing the issule

**Comment by Siomek101** [comment]
screenshot?

**Comment by Siomek101** [comment]
and what are you putting in all fields

**Comment by lucas11222** [comment]
> screenshot?

ok 
![image](https://github.com/face-hh/webx/assets/63660708/6866c46a-aed9-4da1-9dcf-ff59330f0233)

**Comment by Siomek101** [comment]
> > screenshot?
> 
> ok ![image](https://private-user-images.githubusercontent.com/63660708/335687990-6866c46a-aed9-4da1-9dcf-ff59330f0233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzkwMzQsIm5iZiI6MTcxNzE3ODczNCwicGF0aCI6Ii82MzY2MDcwOC8zMzU2ODc5OTAtNjg2NmM0NmEtYWVkOS00ZGExLTlkY2YtZmY1OTMzMGYwMjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE4MDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3M2M1NmE4Y2U1NjBlOWE4ZTBjM2IyYTU1MzM3YmQ0YjZjZDgyNTBiNmZmY2I4Yjk2ODVhYTc1M2I5MDk4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.URDb6wHbZsTWUsCAYuzNAgnqkykkMxcY2UAaoLyF3tU)

huh, and it isn't working?

**Comment by lucas11222** [comment]
yea

> > > screenshot?
> > 
> > 
> > ok ![image](https://private-user-images.githubusercontent.com/63660708/335687990-6866c46a-aed9-4da1-9dcf-ff59330f0233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzkwMzQsIm5iZiI6MTcxNzE3ODczNCwicGF0aCI6Ii82MzY2MDcwOC8zMzU2ODc5OTAtNjg2NmM0NmEtYWVkOS00ZGExLTlkY2YtZmY1OTMzMGYwMjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE4MDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3M2M1NmE4Y2U1NjBlOWE4ZTBjM2IyYTU1MzM3YmQ0YjZjZDgyNTBiNmZmY2I4Yjk2ODVhYTc1M2I5MDk4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.URDb6wHbZsTWUsCAYuzNAgnqkykkMxcY2UAaoLyF3tU)
> 
> huh, and it isn't working?

the same im question me

**Comment by lucas11222** [comment]
ok i tryed root again and dev and same, is that my connection or i live in spain?

**Comment by face-hh** [comment]
Should be fixed now
