### ISSUE TITLE
Feature Request: Auto-Pages + Page Markup Tag

### ISSUE THREAD

**Issue by Scionax** [face-hh/webx#38]
This feature lets Webmasters type something like `<page type="feed" theme="dark">` and have the page automatically load a per-defined browser theme, which includes the fully responsive CSS and built-in theme, with a single tag. Without any CSS, they then have a well-designed page that only requires them to assign content.

Advantages:
- Webmasters can effortlessly create beautiful (and consistent) sites.
- Webmasters don't have to build out full, responsive CSS. It's all done for them.
- Standard CSS is already saved within the browser, saving on data exchange.
- The browser can support mods so that users can choose how default themes are viewed.
- Drastically reduced workload, much faster build time. Lets people focus more on what matters if CSS is not their primary concern.

**Comment by Scionax** [comment]
I should also clarify that there are multiple page types. In this case `feed` was the example, where that would be like a social feed. You could have options like `article` where the content blocks are organized by text, media blocks, etc. You could have others like `workspace`, `game`, `chatbox`, etc.

**Comment by face-hh** [comment]
I feel like this is a pretty niche feature so it's not currently planned
