### ISSUE TITLE
Detected as Trojan:Script/Wacatac.B!ml by Windows Defender

### ISSUE THREAD

**Issue by tiagorangel2011** [face-hh/webx#4]
Windows Defender basically puts your computer into panic mode when you try to run this. And it also deleted the file imediatelly

**Comment by GStudiosX2** [comment]
> Windows Defender basically puts your computer into panic mode when you try to run this. And it also deleted the file imediatelly

For now you can add a exclusion https://support.microsoft.com/en-gb/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process.

**Comment by tiagorangel2011** [comment]
I was able to add an exclusion, but it's pretty annoying.

GStudiosX ***@***.***> escreveu (sexta, 17/05/2024 à(s)
18:34):

**Comment by QuinceTart10** [comment]
The reason why this happens is because Windows Defender flags WinRar self-extracting archives as viruses for some reason. (They're probably used a lot for distributing malware)

It should be fixed by next release, which will hopefully have a different installer 🙂

**Comment by face-hh** [comment]
This has been fixed in v1.2.0
