### ISSUE TITLE
Feature request: <video> tags

### ISSUE THREAD

**Issue by Siomek101** [face-hh/webx#40]
yep

**Comment by lucas11222** [comment]
i think for thah like this <enbed type="(youtube, twiter...">

**Comment by Siomek101** [comment]
didnt see that fetch is already there

**Comment by GStudiosX2** [comment]
> yep

I remember that face said in his Discord that video won't be added until gtk adds some pull request or smth like that

**Comment by GStudiosX2** [comment]
Or it could be that he wants someone to add it to nature for him I'm not sure

**Comment by face-hh** [comment]
Moved to #88
