### ISSUE TITLE
Feature Request: Site Config with Auto-Menu

### ISSUE THREAD

**Issue by Scionax** [face-hh/webx#41]
Sites have a versioned config file that gets sent when the user's version is behind. When a user visits a site, it checks if there is a `config-version` header and matches it against their config version, and re-caches if the version changes.

The site config may contain other valuable data, but the primary focus of this request is the the auto-menu. An example config file may contain something like this:

```
<menu>
#HomePage @/home
#Blog @/blog
##2024 Stuff @/blog/2024
##2023 Stuff @/blog/2023
##2022 Stuff @/blog/2022
#Projects
##My Cool Guitar Solos @/music/guitar
##My Artwork @/art-and-stuff
```

All you need to define is the links, then the browser automatically templates it with the browser's theme. It handles responsiveness so that the user doesn't have to do anything to make it look good.

This can pull directly from the #38 Auto Pages request. For example, one way to implement it would be to have the browser automatically insert a menu tag, e.g. <menu id="main" class="browser_default:dark"/> and then the user could overwrite the CSS if they wanted to, or insert it directly and overwrite its placement entirely.

Advantages:
- Webmasters can effortlessly include a fully responsive menu. No hassle. No coding.
- Cached menus. No need to resend unless expiration is set. Saves on bandwidth.
- No additional CSS is required (but can be optionally overwritten).
- Much faster to implement sites, and entries will be far less likely to appear low effort.

**Comment by face-hh** [comment]
I feel like this is a pretty niche feature so it's not currently planned

A Lua function to get the browser version may be implemented
