### ISSUE TITLE
liblua not found

### ISSUE THREAD

**Issue by Milk-Cool** [face-hh/webx#44]
Okay, enough with the "funny" stuff, time for an actual issue.

```
./Bussin.Napture.LINUX: error while loading shared libraries: liblua.so.5.4: cannot open shared object file: No such file or directory
```
I already have `lua5.4`, `liblua5.4-dev` and `liblua5.4-0` installed. Do i have to install something else as well?

**Comment by Milk-Cool** [comment]
google doesn't seem to help too :(

**Comment by Milk-Cool** [comment]
Duplicate of #21 i guess? Or should the issue be moved here?

**Comment by Milk-Cool** [comment]
the latest version of gtk4 for ubuntu is 4.12 while rust requires at least 4.13:
```
> PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags gtk4 gtk4 >= 4.13
```
i'll try updating the system and we'll see if it helps

**Comment by Milk-Cool** [comment]
it broke my system

**Comment by Jajoo2** [comment]
> it broke my system

oh, that's sad
guess i won't try that then

**Comment by Milk-Cool** [comment]
@Jajoo2 Actually I was able to fix the broken packages using an installation USB, it probably won't break anything for you though.

**Comment by Milk-Cool** [comment]
Also, compiling the browser works now. Closing the issue.
