### ISSUE TITLE
IMPORTANT: websites stopped working bruh

### ISSUE THREAD

**Issue by Siomek101** [face-hh/webx#45]
I went to my domain bubble.it, and it didnt find it? Then i went to dingle.it, and it still didnt find it. Every website broke for some reason. After restarting it seems to be fixed until i go to my website
Wth?
![image](https://github.com/face-hh/webx/assets/94121336/2a92a7e4-e1b7-4cc6-b296-417ddf556edb)

**Comment by Siomek101** [comment]
Update: only the search loads once. Never again, not even working

**Comment by weeniemount** [comment]
https://github.com/face-hh/webx/issues/34

**Comment by Siomek101** [comment]
wdym bro

**Comment by Siomek101** [comment]
![image](https://github.com/face-hh/webx/assets/94121336/b3cecb32-3a83-4809-8830-18b785ec9090)

**Comment by weeniemount** [comment]
images are broken on windows, thats why im mentioned that
you need to compile it for windows

**Comment by Siomek101** [comment]
> images are broken on windows, thats why im mentioned that you need to compile it for windows

its not about IMAGES
are you even reading the issue?

**Comment by weeniemount** [comment]
wdym about broken websites then? can you explain more, you didnt provide a lot of detail

**Comment by Siomek101** [comment]
> wdym about broken websites then? can you explain more, you didnt provide a lot of detail

try going to a random website, for me it doesnt work and for another person

**Comment by Siomek101** [comment]
ok seems to be fixed i think, i dunno why it didnt work

**Comment by jdev082** [comment]
The API that is used to determine if a page exists or not was down
