### ISSUE TITLE
dingle.it not showing search results and displaying blank areas where searchs would be

### ISSUE THREAD

**Issue by craft-o-s-project** [face-hh/webx#46]

**Comment by weeniemount** [comment]
it seems like there is an error with the request but im not sure
![image](https://github.com/face-hh/webx/assets/59868100/c045da5f-1166-4067-8984-7756bf8d8c70)

**Comment by craft-o-s-project** [comment]
he might have broke the search engine...

**Comment by face-hh** [comment]
The search engine is temporarily down
