### ISSUE TITLE
servers for registering domains and dingle search engine seem like they are down

### ISSUE THREAD

**Issue by craft-o-s-project** [face-hh/webx#48]

**Comment by craft-o-s-project** [comment]
only the scripts dont work

**Comment by face-hh** [comment]
The search engine is temporarily down for maintenance

**Comment by craft-o-s-project** [comment]
just to let you know is that why domain registering is not working?

**Comment by craft-o-s-project** [comment]
because tlds say loading...

**Comment by Smartlinuxcoder** [comment]
You can see the uptime [here](https://uptime.smartlinux.xyz/status/face)
