### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by TheGallium** [face-hh/webx#51]
It should be less of a pain than windows

**Comment by RaphaelDarley** [comment]
It works for me, just need to brew install things if missing

**Comment by RaphaelDarley** [comment]
brew install gtk4
brew install lua@5.4
brew install libadwaita

**Comment by Qtechinnovation** [comment]
how did you get it to compile? install script failed for me on a command not found.

**Comment by face-hh** [comment]
Will be added in the readme in a bit
