### ISSUE TITLE
Idea: Be able to open files using the file://

### ISSUE THREAD

**Issue by TheOddCell** [face-hh/webx#59]
Just what the title said: I would like to be able to open files!

(Also, add a little file explorer page for folders, and be able to use .buss or .btml or whatever files!)

**Comment by craft-o-s-project** [comment]
i want that

**Comment by GStudiosX2** [comment]
> Just what the title said: I would like to be able to open files!
> 
> (Also, add a little file explorer page for folders, and be able to use .buss or .btml or whatever files!)

You can go to a folder that has a index.html in it but ATM can't open any file

**Comment by Jajoo2** [comment]
Can't you just use your own file browser?

**Comment by Siomek101** [comment]
> Just what the title said: I would like to be able to open files!
> 
> (Also, add a little file explorer page for folders, and be able to use .buss or .btml or whatever files!)



> Just what the title said: I would like to be able to open files!
> 
> (Also, add a little file explorer page for folders, and be able to use .buss or .btml or whatever files!)

BSML - Buss Markup Language

**Comment by TheOddCell** [comment]
Closed? Version 1.2.2 of Napture has the file part, and the executable is standalone(ish) program so no BSML files, but it seems like this has been done!
