### ISSUE TITLE
stuck on gtk4 compiling

### ISSUE THREAD

**Issue by EducatedSuddenBucket** [face-hh/webx#64]
I was compiling this for 5 hours( I have a old pc) and now its stuck on 220/243 gtk4 for now i have closed it

**Comment by GStudiosX2** [comment]
Uh I think it took like 5-10 minutes for me fresh to build this on my phone

**Comment by EducatedSuddenBucket** [comment]
if you have compiled it on on android can you give me the apk so i can test the app

**Comment by GStudiosX2** [comment]
> if you have compiled it on on android can you give me the apk so i can test the app

It's not a APK it's a Linux arm64 app I was using it in proot-distro with vnc

**Comment by face-hh** [comment]
Sorry but this is not a valid issue. There's no way to replicate this and it's probably just your computer being super slow
