### ISSUE TITLE
Dingle shows blank rectangles instead of search results

### ISSUE THREAD

**Issue by Milk-Cool** [face-hh/webx#71]
![image](https://github.com/face-hh/webx/assets/43724263/f4618429-496a-46e1-be10-7221ca88e4d0)

It could be related to my gtk theme i think? It's the default ubuntu 24.04 one tho.

**Comment by bocik1** [comment]
someone created a milion of domains and dingle cannot process it

**Comment by Milk-Cool** [comment]
ohh... that's a shame. are we able to register new ones at least?

**Comment by TheOddCell** [comment]
Yep! Just registered oddcell.dev! It works!

**Comment by Milk-Cool** [comment]
Okay, thanks! Idk if I should close the issue so I'll leave this open until the problem gets fixed

**Comment by craft-o-s-project** [comment]
i might make a search engine when the browser is fixxed

**Comment by 20wsdwkder309** [comment]
Same issue

**Comment by face-hh** [comment]
Fixed now

**Comment by 20wsdwkder309** [comment]
oki
