### ISSUE TITLE
can't even open webx

### ISSUE THREAD

**Issue by NoteSwiper** [face-hh/webx#73]
when i tries to open `BussinNapturePortable.exe` in Another hard drives, it fails to lookup `ProgramExecutable`, it says
```
I¥www¥BussinNapturePortable¥App¥AppInfo¥Launcher¥BussinNapturePortable.ini is missing [Launch]:PortableExecutable - what am I to launch?
```

**Comment by QuinceTart10** [comment]
Uhh, try reinstalling the app in a folder that is maybe something like C:\BussinNapturePortable

**Comment by NoteSwiper** [comment]
i had solved this problem by making the administrator permission to its launcher!
sorry for my useless mind!
