### ISSUE TITLE
Can't update my site

### ISSUE THREAD

**Issue by PaologGithub** [face-hh/webx#77]
I can't update my site on register.it

I put my key, my github.

The problem: or it crashes Bussin_Napture,
or it says this:
Loading...Result will appear here after you press Done.
Enter the CAPTCHA code...

So, I can't update my site...

**Comment by Bokobelin** [comment]
Same problem on issue #78

**Comment by face-hh** [comment]
fixed now

**Comment by PaologGithub** [comment]
For people who has the same problem, download the latest version
