### ISSUE TITLE
Register.it not working

### ISSUE THREAD

**Issue by AnubhavSingh0708** [face-hh/webx#78]
The console is only showing. Please enter capta with the captcha loading

**Comment by lucas11222** [comment]
me too 
![image](https://github.com/face-hh/webx/assets/63660708/1b4e8136-3ab4-4615-9a6d-c9eb07ea36fe)

**Comment by face-hh** [comment]
What napture version?

**Comment by lucas11222** [comment]
the new

**Comment by face-hh** [comment]
What does it say when you do CTRL SHIFT P

**Comment by lucas11222** [comment]
im in windows and nothing

**Comment by Bokobelin** [comment]
Yes me too !

**Comment by Bokobelin** [comment]
On version 1.2.2

**Comment by 20wsdwkder309** [comment]
Same issue

**Comment by hi101000** [comment]
same issue

**Comment by face-hh** [comment]
fixed
