### ISSUE TITLE
[Feature request] Numbers on domain names

### ISSUE THREAD

**Issue by inventionpro** [face-hh/webx#79]
Normal https allows numbers, why the better buss protocol doesn't
(should be easy to implement just change the regex)

**Comment by face-hh** [comment]
Numbers will make moderation infinitely harder.

**Comment by lucas11222** [comment]
> Numbers will make moderation infinitely harder.

thats why i cant make lucas11.root

**Comment by inventionpro** [comment]
> Numbers will make moderation infinitely harder.

how about a way to have any text in your domain but it requires manual verification (maybe a patreon only thing)
