### ISSUE TITLE
Forever loading

### ISSUE THREAD

**Issue by 20wsdwkder309** [face-hh/webx#84]
When trying to register on register,it the captcha is forever loading

**Comment by face-hh** [comment]
Make sure you're using v1.2.2

**Comment by 20wsdwkder309** [comment]
I am

**Comment by face-hh** [comment]
Can you try now? The servers have been reset

**Comment by 20wsdwkder309** [comment]
https://github.com/face-hh/webx/assets/164775106/15796792-1580-4748-9888-03e23114c064

same thing

**Comment by 20wsdwkder309** [comment]
wait i am fucking dumb

**Comment by 20wsdwkder309** [comment]
"Currently broken on pre-built Windows executables"

**Comment by 20wsdwkder309** [comment]
I'm closing this issue
