### ISSUE TITLE
Nothing but the default search engine only loads

### ISSUE THREAD

**Issue by computerblade-official** [face-hh/webx#86]
Sys: Arch Linux 202405 w/ budgie DE.
![image](https://github.com/face-hh/webx/assets/66473206/98da17a0-b4b8-4902-8bd0-8691065ad889)
The above error keeps on showing even after reinstalling.
I am not sure why this happens...
Also now the search engine as well doesnt load, shows the same error.
Thank you!

**Comment by adricom231** [comment]
Same on Windows 10

**Comment by craft-o-s-project** [comment]
yeah

**Comment by craft-o-s-project** [comment]
https://uptime.smartlinux.xyz/status/face
this is the uptime

**Comment by craft-o-s-project** [comment]
bro the domains api does not want to load

**Comment by craft-o-s-project** [comment]
error 504...

**Comment by craft-o-s-project** [comment]
@face-hh

**Comment by MattiaIlPotenteReal** [comment]
you are lucky that at least something open, for me it only opens a small white window

**Comment by face-hh** [comment]
This has been fixed, the VPS was updated

**Comment by computerblade-official** [comment]
Thank you.
