### ISSUE TITLE
Feature: allow alternate website sources

### ISSUE THREAD

**Issue by PPPDUD** [face-hh/webx#93]
Your WebX project is fascinating, but I have concerns about the centralized structure that you're using. With the current system, any Github employee can easily tamper with WebX sites.

I propose that three servers shall be held. Each one will have its own rules, and will be hosted by a different provider. WebX developers would add their sites to each server, and if one server goes down or is compromised, the other two will still work.

If this proposal is implemented, I may offer to host a server for you.

**Comment by rathlinus** [comment]
You can selfhost already

**Comment by PPPDUD** [comment]
> [rathlinus](/rathlinus)
That's great! Thank you!
